services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logistics
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
    - "3306:3306"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 20

  auth_svc:
    build: ./auth
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: root
      DB_NAME: logistics
      JWT_SECRET: secret123
      PORT: 3001
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    ports: ["3001:3001"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/login"] # devuelve 404 pero responde
      interval: 10s
      timeout: 3s
      retries: 10

  vehiculos_svc:
    build: ./vehiculos
    environment:
      MONGO_URI: mongodb://mongo:27017/vehiculosdb
      JWT_SECRET: secret123
      PORT: 3002
      GRPC_PORT: 50051
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    ports: ["3002:3002","50051:50051"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3002/vehiculos"]
      interval: 10s
      timeout: 3s
      retries: 15

  envios_svc:
    build: ./envios
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: root
      DB_NAME: logistics
      PORT: 3003
      VEHICULOS_GRPC_HOST: vehiculos_svc
      VEHICULOS_GRPC_PORT: 50051
    depends_on:
      mysql:
        condition: service_healthy
      vehiculos_svc:
        condition: service_started
    restart: unless-stopped
    ports: ["3003:3003"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3003/graphql"]
      interval: 10s
      timeout: 3s
      retries: 15

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      auth_svc:
        condition: service_started
      vehiculos_svc:
        condition: service_started
      envios_svc:
        condition: service_started
    ports: ["80:80"]
    restart: unless-stopped
